# Generated by Django 3.0.6 on 2020-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
