# Generated by Django 3.0.6 on 2020-06-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Designer',
        ),
    ]
